### ISSUE TITLE
Incorrect building of IPK packages

### ISSUE THREAD

**Issue by graterlia** [oe-alliance/oe-alliance-core#383]
After upgrading to a newer version of OpenEmbedded Core (a few days ago) there is quite a big mistake. It certainly occurs when compiling in Debian 9.x and Ubuntu 16.04/18.04.
The error concerns the addition of "-S" on line 652 in the openembedded-core/meta/classes/package.bbclass file
By adding "-S", almost all packages containing BASH scripts/binary files contain corrupted versions. The contents of files are dots or other "trash".
It's enough to remove "-S" and everything compiles nicely.
Error confirmed for MIPS32EL. I did not test for another architecture.

**Comment by christophecvr** [comment]
Yes I looked it up and indeed using the -S there are more reports of it sometimes it threats a non sparse file as a sparse with result that the copied will be corrupted. (goes up for tar --create and cp commands)
Think it's best to create always without -S option . the disadvantage is That in case there are sparse files into the package that they will be copied back to their full size (with the empty blocks) and the tar reslut will have a bigger hd space then the original file. But this last will not break anything, using -S may make a plugin unusable and corrupt.

**Comment by christophecvr** [comment]
@graterlia 
You should made a more detailed build report about this issue . With an example package where it happens. I now quit a while ago did suffer from corrupt (eighter partially corrupt backup) After a hd crash due to stuck hd I did lost a lot of script bash files and was not happy about that. The tar was created with using -S, so indeed I never use that anymore to backup. Sure if report is complete with example it will be passed to openembedded . The change was done in openembedded on commit : 
"http://git.openembedded.org/openembedded-core/commit/?id=d86da5ae386a8129a966a53901de160823f4d250" 7 days ago by Richard Purdie <richard.purdie@linuxfoundation.org> msg package: Fix file copying to preserve sparse files
