### ISSUE TITLE
nextp3 - e2 compile error after glibc initial removed from oecore

### ISSUE THREAD

**Issue by nickersk** [oe-alliance/oe-alliance-core#442]
after glibc initial was removed from oecore i get this error while do_compile  enigma2.bb 
:  crt1.o: undefined reference to symbol '_gp'
i am playing with it few days, but still have no idea what has to be fixed ...

**Comment by atvcaptain** [comment]
found this, https://patchwork.ozlabs.org/patch/312275/  

but no idea its same issue with openssl

i start now build fresh need some time before e2 build start

**Comment by nickersk** [comment]
building oatv image for vusolose, looks like libv3ddriver.so is causing this issue (it is part of graphics drivers). other mipsel machines can be affected too ... probably, depending on supplier drivers. still looks like it can be somehow fixed globally, because it started just after glibc initial being removed from oecore.

**Comment by atvcaptain** [comment]
i build osmio4k use too libv3 addon from edision but no build issue, i start build now vusolose too

**Comment by nickersk** [comment]
pls update oecore to latest master first - glibc initial was removed after commit 956 ...

**Comment by nickersk** [comment]
it's related to this maybe: https://bugzilla.yoctoproject.org/show_bug.cgi?id=13097

**Comment by atvcaptain** [comment]
SHA-1: 62b7308b8c4d2b439a15a4f7cbc6f823077bb0be

* gcc: Drop gcc-cross-initial and use gcc-cross instead

We need a libgcc to build glibc. Tranditionally we therefore build
a non-threaded and non-shared compiler (gcc-cross-initial), then use
that to build libgcc-initial which is used to build glibc which we can
then build gcc-cross and libgcc against.

Firstly, we can drop the glibc dependency from gcc-cross, *if* we make
two changes:

a) specify the minimum glibc version to support in a configure option
b) create a dummy limits.h file so that later when glibc creates one,
   the headers structure has support for it. We can do this with a simple
   empty file

Once gcc-cross is libc independent, we can use it to build both
libgcc-initial and then later libgcc.

libgcc-initial is tricky as we need to imitate the non-threaded and
non-shared case. We can do that by hacking the threading mode back to
"single" even if gcc reports "posix" and disable libc presence for the
libgcc-intial build. We have to create the dummy limits.h to avoid
compiler errors from a missing header.

glibc will fail to link with libgcc-initial due to a missing "exception
handler" capable libgcc (libgcc_eh.a). Since we know glibc doesn't need
any exception handler, we can safely symlink to libgcc.a.

With those changes, gcc-cross can be used in all places and we only need
one build of gcc for each architecture.

For some reason ifunc was being disabled on mips prior to these changes
but afterwards became enabled but caused assertion failures. This is
therefore disabled until we can debug that.

**Comment by atvcaptain** [comment]
now i have many fetch errors

  /home/oe1/nextp3/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2-channelsettings/enigma2-plugin-settings-henksat-13e-19e-23e-28e-42e-7e.bb:do_fetch
  /home/oe1/nextp3/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2-channelsettings/enigma2-plugin-settings-gigablue-wilhelmtel.bb:do_fetch
  /home/oe1/nextp3/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2-plugins/e2openplugins/enigma2-plugin-extensions-permanentvfdclock.bb:do_fetch
  /home/oe1/nextp3/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2-channelsettings/enigma2-plugin-settings-vhannibal.motor.and.dtt.roma.bb:do_fetch
  /home/oe1/nextp3/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2-channelsettings/enigma2-plugin-settings-vhannibal.dual.feeds.and.dtt.torino.bb:do_fetch

**Comment by nickersk** [comment]
this is related to sqlite db setup in bitbake (oe guys changed that few days ago). u need to run bitbake more times to get through this locking protocol errors...

**Comment by atvcaptain** [comment]
build arm fresh with last master and finish without error

**Comment by atvcaptain** [comment]
https://github.com/oe-alliance/oe-alliance-core/commit/31d881bcd6de75e87de6c0baed03e826f0362f02

build running , i have first remove uianimation only vu have it

**Comment by nickersk** [comment]
vusolose e2 compiled ok without uianimation

**Comment by atvcaptain** [comment]
for the fetch issue i add a bug: https://bugzilla.yoctoproject.org/show_bug.cgi?id=13108

**Comment by nickersk** [comment]
fetch bug is resolved in bitbake master-next branch... so it will be available in master soon (at least i hope) :-D

**Comment by nickersk** [comment]
fetch patch is in master branch now, so we can update OE submodules ....
