### ISSUE TITLE
Ipv6 over openwebif stream

### ISSUE THREAD

**Issue by gomble** [oe-alliance/oe-alliance-core#49]
Gigablue 800 hd ue
It is not possible to stream with ipv6 over openwebif.
I come with the ipv6 adress in to openwebif but if i click on to the tv picon which opens vlc, i get an error that vlc can´t access the adress. I scanned the Port 8001 and it seems to be that is not opened. If i test it with ipv4 it works.

**Comment by Schimmelreiter** [comment]
This is a limitation of E2 itself.
I keep reporting this again and again and still it's handled with far less priority than it deserves (I've set up dozens of E2 boxes behind IPv6-only internet connections already).

Someone hopefully will finally fix it here:
https://github.com/oe-alliance/oe-alliance-enigma2/tree/master/lib/network
by modifying the C++ code to use Dual Stack sockets rather than IPv4 only ones.
